import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { ExternalLink } from "lucide-react";

interface Tool {
  name: string;
  image: string;
  description: string;
  links: { label: string; url: string }[];
}

const tools: Tool[] = [
  {
    name: "CaRinDB",
    image: "CaRinDB.png",
    description: "CaRinDB is an interactive database designed to streamline cancer mutation research by integrating data from The Cancer Genome Atlas (TCGA) and advanced structural analysis tools, along with advanced effect predictions and molecular features such as Residue Interaction Networks (RINs) derived from Protein Data Bank experimental structures and AlphaFoldDB computational models. Covering 33 distinct cancer types, CaRinDB offers a broad spectrum of insights into cancer mutation dynamics.",
    links: [{ label: "Go to CaRinDB", url: "https://bioinfo.imd.ufrn.br/CaRinDB/" }]
  },
  {
    name: "SlyTheRINs",
    image: "SlytheRINs.png",
    description: "SlytheRINs is an interactive Python web application built with Streamlit, designed to analyze and compare protein Residue Interaction Networks (RINs). These graphs represent the amino acid residues as the nodes and their chemical interactions as the edges. They can be easily generated from a single or multiple protein structures, using computational modeling methods, normal-based mode, or molecular dynamics simulation. SlytheRINs provides an analysis dashboard to explore and compare network parameters, identify significant residue-level changes across different conformations, analyze chemical interaction types, and integrate these findings with predicted mutation effects from AlphaMissense (in the case of human proteins).",
    links: [{ label: "Go to SlyTheRins", url: "https://slytherins.streamlit.app" }]
  },
  {
    name: "The Room of Conformations (RoC)",
    image: "RoC-Logo.png",
    description: "A user-friendly desktop tool for generating all-atom protein conformational ensembles using Normal Mode Analysis.",
    links: [
      { label: "Go to RoC (GitHub)", url: "https://github.com/evomol-lab/RoC" },
      { label: "Go to RoC (Google Colab)", url: "https://colab.research.google.com/drive/1jd3qgAZPF9bWxlcCjYURpFQAEYW102Y5?usp=sharing" }
    ]
  },
  {
    name: "RevelioPlots",
    image: "RevelioPlots.png",
    description: "RevelioPlots is an interactive web application designed for the quality assessment of protein structure models. By parsing Crystallographic Information Files (.cif or .mmcif), the app provides a suite of intuitive visualizations centered around the per-residue Local Distance Difference Test (pLDDT) score, a key metric for model confidence, particularly in structures generated by tools like AlphaFold.",
    links: [
      { label: "Go to RevelioPlots (App)", url: "https://revelioplots.streamlit.app" },
      { label: "Go to RevelioPlots (GitHub)", url: "https://github.com/jpmslima/RevelioPlots" }
    ]
  },
  {
    name: "HufflePlots",
    image: "HufflePlots.jpg",
    description: "HufflePlots is a simple and interactive tool to visualize, analyze and compare RMSD and RMSF plots of protein structural trajectories data from Molecular Dynamics or Normal mode-based geometric simulations.",
    links: [{ label: "Go to HufflePlots", url: "https://protplots.streamlit.app" }]
  },
  {
    name: "Differential Expression Diagonal Alley (DDEA)",
    image: "DDEA.png",
    description: "DDEA is a simple Streamlit application to analyze Case x Control gene expression output data from GEO. Allows users to upload a .tsv file, a custom gene list (optional), and specify a comparison string, with controls in a sidebar. DDEA then plots differentially expressed genes using Plotly and displays their p-values.",
    links: [{ label: "Go to DDEA", url: "https://ddealley.streamlit.app/" }]
  },
  {
    name: "Rictusempra",
    image: "Rictusempra.png",
    description: "Rictusempra is a web-based cheminformatics tool for interactively visualizing small molecules and calculating their most likely protonation state at a given physiological pH. It provides a simple interface to generate 2D and 3D molecular structures and prepare them for further computational chemistry tasks like molecular docking or simulation.",
    links: [{ label: "Go to Rictusempra", url: "https://rictusempra.streamlit.app" }]
  },
  {
    name: "Marauder's GenoMap",
    image: "MaraudersGenoMap.png",
    description: "A comprehensive pipeline for the discovery of protein families in de novo assembled genomes and transcriptomes.",
    links: [{ label: "Go to Marauder's GenoMap (GitHub)", url: "https://github.com/evomol-lab/MaraudersGenoMap" }]
  },
  {
    name: "The Pensieve Plotter",
    image: "PensievePlotter.png",
    description: "An interactive tool for visualizing Extended Bayesian Skyline Plots (EBSP) from BEAST log files.",
    links: [{ label: "Go to The Pensieve Plotter", url: "https://pensieveplotter.streamlit.app/" }]
  }
];

const ToolsTab = () => {
  return (
    <div className="animate-fade-in space-y-6">
      <Card className="shadow-medium border-border/50 overflow-hidden">
        <div className="h-2 bg-gradient-primary" />
        <CardContent className="p-8">
          <h2 className="text-3xl font-bold text-foreground mb-4">
            Our Bioinformatics tutorials page:
          </h2>
          <Button asChild className="bg-gradient-primary hover:opacity-90 transition-opacity text-white">
            <a 
              href="https://jpmslima.github.io" 
              target="_blank" 
              rel="noopener noreferrer"
              className="flex items-center gap-2"
            >
              Tutoriais BioinfoX
              <ExternalLink className="h-4 w-4" />
            </a>
          </Button>
        </CardContent>
      </Card>

      <Card className="shadow-medium border-border/50 overflow-hidden">
        <div className="h-2 bg-gradient-primary" />
        <CardContent className="p-8">
          <h2 className="text-3xl font-bold text-foreground mb-2">Our tools:</h2>
          <p className="text-foreground/80 mb-8">
            "EvoMol-Lab has a series of <strong><em>"magic"</em></strong> tools to help you with your work and analyses.
          </p>

          <div className="space-y-8">
            {tools.map((tool, index) => (
              <div 
                key={index}
                className="flex flex-col md:flex-row gap-6 pb-8 border-b border-border/50 last:border-0 group hover:bg-accent/30 transition-colors rounded-lg p-4 -mx-4"
              >
                <div className="flex-shrink-0 mx-auto md:mx-0">
                  <img 
                    src={tool.image} 
                    alt={tool.name}
                    className="w-28 h-28 object-contain rounded-lg bg-white p-2 shadow-subtle"
                  />
                </div>
                
                <div className="flex-1 space-y-3">
                  <h3 className="text-2xl font-semibold text-secondary">{tool.name}</h3>
                  <p className="text-foreground/80 text-justify leading-relaxed">
                    {tool.description}
                  </p>
                  <div className="flex flex-wrap gap-3">
                    {tool.links.map((link, linkIndex) => (
                      <Button 
                        key={linkIndex}
                        asChild 
                        variant="outline"
                        className="hover:bg-primary hover:text-primary-foreground transition-colors border-primary/30"
                      >
                        <a 
                          href={link.url} 
                          target="_blank" 
                          rel="noopener noreferrer"
                          className="flex items-center gap-2"
                        >
                          {link.label}
                          <ExternalLink className="h-3.5 w-3.5" />
                        </a>
                      </Button>
                    ))}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
};

export default ToolsTab;
