site_name: EvoMol-Lab's Teaching Resources
site_url: https://evomol-lab.github.io/tutorials
site_author: EvoMol-Lab
site_description: Tutoriais básicos de Bioinformática

nav:
  - Página Inicial: index.md
  - Representação Computacional de Biomoléculas: demo.md
  - Sobre o grupo: aboutus.md
  - Tutoriais Iniciais de Bioinformática: 
    - Inicial: basic1.md
    - Introdução a linha de comando UNIX: 101.md
    - Manipulando dados na CLI: 102.md
    - Introdução a CLI e ao Google Colab: CLI-Colab.md
    - Introdução ao GenBank: 103.md
    - Buscas de Similaridade: 104.md
    - Alinhamento entre pares de sequências: 105.md
    - Alinhamento Múltiplo de Sequências: 106-MSA.md
    - NCBI/GenBank via CLI: 107-NCBI-CLI.md
    - BLAST via CLI: 108-BLAST-CLI.md
    - Comandos Básicos em SQL: 109-SQL.md
    - Introdução ao R usando o Google Colab: r-colab.md
    - Integração de Bancos - Exemplo: enzima-annot.md
    - Bancos de dados de Mutações e Polimorfismos: dbsnp.md
    - Explorando Vias Metabólicas: KEGG.md
    - Bancos de Dados de Informação Proteica: 110-BDs.md
    - Modelagem Computacional de Proteínas: 111-Modelagem.md
    - Primeiros Passos no MEGA: 112-MEGAX.md
    - Navegando por Genomas: 113-Genomes.md
    - Videoaulas: video.md
  - Bioinformática Estrutural:
    - Inicial: basic2.md
    - Slides de Acompanhamento: slides.md
    - Programas e Ferramentas: tools.md
    - Visualização Computacional de Moléculas: STR1-Visualizacao.md
    - Informações a partir da estrutura primária: STR2-pred.md
    - Predição de Epítopos: STR22-Epitopos.md
    - Modelagem 101: STR3-Model1.md
    - Modelagem 102: STR4-Model2.md
    - Modeller-CLI: STR5-Model3.md
    - Métodos baseados em IA: STR6-AlphaFold.md
    - MDA: STR7-MDA.md
    - Avaliação dos Modelos: STR8-Aval.md
    - EM/CryoEM fitting: STR9-EM.md
    - RINs: STR10-RINs.md
    - APBS: STR11-APBS.md
    - Proteínas de Membrana: STR12-Memb.md
    - Autodock (básico): STR13-Dock1.md
    - Docking: STR14-Dock2.md
    - Virtual Screening: STR15-VS1.md
    - Introdução a Dinâmica Molecular: STR23-MDIntro.md
    - Modelos de Pequenas Moléculas: STR16-EGB1.md
    - Análise conformacional: STR17-EGB2.md
    - Docking Automático: STR18-EGB3.md
    - Posicionamento Manual: STR19-EGB4.md
    - Dinâmica Molecular: STR20-EGB5.md
    - VS-2: STR21-EGB6.md
    - Complements: comps.md
  - Análise Evolucionária de Sequências (Evolução Molecular):
    - Análise de Saturação de Substituições: satsub.md
    - Escolha do Modelo de Substituição: bestfit.md
    - Usando o BEAST: BEAST.md
  - Diplomado - UChile: 
    - Home: Presentation.md
    - Slides: UC_slides.md
    - Files and References: Material.md
    - First Tutorial: First_Tutorial.md
    - Analysis of Substitution Saturation: Substitution_saturation.md
    - Test of the Best-Fit Models: ModelTest.md
    - Using MEGAX: MEGAX.md
    - Using BEAST: 1st_BEAST.md
    - Phylodynamics using EBSP: BEAST+EBSP.md
    - Using IQ-Tree: IQTree.md

theme:
  name: material
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  alternate:
    - name: Português
      link: /tutorials/
      lang: pt
    - name: English
      link: /tutorials/en/
      lang: en
    - name: Español
      link: /tutorials/es/
      lang: es

plugins:
  - search
  - i18n:
      default_language: pt
      docs_structure: suffix
      fallback_to_default: true
      languages:
        - locale: pt
          name: Português
          build: true
          default: true
        - locale: en
          name: English
          build: true
          nav_translations:
            Página Inicial: "Home Page"
            Representação Computacional de Biomoléculas: "Computational Representation of Biomolecules"
            Sobre o grupo: "About the group"
            Tutoriais Iniciais de Bioinformática: "Initial Bioinformatics Tutorials"
            Inicial: "Initial"
            Introdução a linha de comando UNIX: "Introduction to UNIX command line"
            Manipulando dados na CLI: "Manipulating data in CLI"
            Introdução a CLI e ao Google Colab: "Introduction to CLI and Google Colab"
            Introdução ao GenBank: "Introduction to GenBank"
            Buscas de Similaridade: "Similarity Searches"
            Alinhamento entre pares de sequências: "Pairwise Sequence Alignment"
            Alinhamento Múltiplo de Sequências: "Multiple Sequence Alignment"
            Comandos Básicos em SQL: "Basic SQL Commands"
            Introdução ao R usando o Google Colab: "Introduction to R using Google Colab"
            Integração de Bancos - Exemplo: "Database Integration - Example"
            Bancos de dados de Mutações e Polimorfismos: "Mutation and Polymorphism Databases"
            Explorando Vias Metabólicas: "Exploring Metabolic Pathways"
            Bancos de Dados de Informação Proteica: "Protein Information Databases"
            Modelagem Computacional de Proteínas: "Computational Protein Modeling"
            Primeiros Passos no MEGA: "First Steps in MEGA"
            Navegando por Genomas: "Navigating Genomes"
            Videoaulas: "Video classes"
            Bioinformática Estrutural: "Structural Bioinformatics"
            Slides de Acompanhamento: "Accompanying Slides"
            Programas e Ferramentas: "Programs and Tools"
            Visualização Computacional de Moléculas: "Computational Visualization of Molecules"
            Informações a partir da estrutura primária: "Information from the primary structure"
            Predição de Epítopos: "Epitope Prediction"
            Modelagem 101: "Modeling 101"
            Modelagem 102: "Modeling 102"
            Métodos baseados em IA: "AI-based methods"
            Avaliação dos Modelos: "Model Evaluation"
            Proteínas de Membrana: "Membrane Proteins"
            Autodock (básico): "Autodock (basic)"
            Introdução a Dinâmica Molecular: "Introduction to Molecular Dynamics"
            Modelos de Pequenas Moléculas: "Small Molecule Models"
            Análise conformacional: "Conformational analysis"
            Docking Automático: "Automatic Docking"
            Posicionamento Manual: "Manual Positioning"
            Dinâmica Molecular: "Molecular Dynamics"
            Análise Evolucionária de Sequências (Evolução Molecular): "Evolutionary Sequence Analysis (Molecular Evolution)"
            Análise de Saturação de Substituições: "Substitution Saturation Analysis"
            Escolha do Modelo de Substituição: "Choice of Substitution Model"
            Usando o BEAST: "Using BEAST"
        - locale: es
          name: Español
          build: true
          nav_translations:
            Página Inicial: "Página de Inicio"
            Representação Computacional de Biomoléculas: "Representación Computacional de Biomoléculas"
            Sobre o grupo: "Sobre el grupo"
            Tutoriais Iniciais de Bioinformática: "Tutoriales Iniciales de Bioinformática"
            Inicial: "Inicial"
            Introdução a linha de comando UNIX: "Introducción a la línea de comandos UNIX"
            Manipulando dados na CLI: "Manipulación de datos en CLI"
            Introdução a CLI e ao Google Colab: "Introducción a CLI y Google Colab"
            Introdução ao GenBank: "Introducción a GenBank"
            Buscas de Similaridade: "Búsquedas de Similitud"
            Alinhamento entre pares de sequências: "Alineamiento de pares de secuencias"
            Alinhamento Múltiplo de Sequências: "Alineamiento Múltiple de Secuencias"
            Comandos Básicos em SQL: "Comandos Básicos en SQL"
            Introdução ao R usando o Google Colab: "Introducción a R usando Google Colab"
            Integração de Bancos - Exemplo: "Integración de Bases de Datos - Ejemplo"
            Bancos de dados de Mutações e Polimorfismos: "Bases de datos de Mutaciones y Polimorfismos"
            Explorando Vias Metabólicas: "Explorando Vías Metabólicas"
            Bancos de Dados de Informação Proteica: "Bases de Datos de Información Proteica"
            Modelagem Computacional de Proteínas: "Modelado Computacional de Proteínas"
            Primeiros Passos no MEGA: "Primeros Pasos en MEGA"
            Navegando por Genomas: "Navegando por Genomas"
            Videoaulas: "Clases en video"
            Bioinformática Estrutural: "Bioinformática Estructural"
            Slides de Acompanhamento: "Diapositivas de Apoyo"
            Programas e Ferramentas: "Programas y Herramientas"
            Visualização Computacional de Moléculas: "Visualización Computacional de Moléculas"
            Informações a partir da estrutura primária: "Información a partir de la estructura primaria"
            Predição de Epítopos: "Predicción de Epítopos"
            Modelagem 101: "Modelado 101"
            Modelagem 102: "Modelado 102"
            Métodos baseados em IA: "Métodos basados en IA"
            Avaliação dos Modelos: "Evaluación de Modelos"
            Proteínas de Membrana: "Proteínas de Membrana"
            Autodock (básico): "Autodock (básico)"
            Introdução a Dinâmica Molecular: "Introducción a la Dinámica Molecular"
            Modelos de Pequenas Moléculas: "Modelos de Pequeñas Moléculas"
            Análise conformacional: "Análisis conformacional"
            Docking Automático: "Docking Automático"
            Posicionamento Manual: "Posicionamiento Manual"
            Dinâmica Molecular: "Dinámica Molecular"
            Análise Evolucionária de Sequências (Evolução Molecular): "Análisis Evolutivo de Secuencias (Evolución Molecular)"
            Análise de Saturação de Substituições: "Análisis de Saturación de Sustituciones"
            Escolha do Modelo de Substituição: "Elección del Modelo de Sustitución"
            Usando o BEAST: "Usando BEAST"
